name: Generate HACS Data

on:
  workflow_dispatch:
    inputs:
      forceRepositoryUpdate:
        description: 'Force repository update'
        required: false
        default: 'False'
        type: choice
        options:
          - "False"
          - "True"
  schedule:
    - cron: "0 */2 * * *"

concurrency:
  group: category-data

jobs:
  category-data:
    runs-on: ubuntu-latest
    if: github.repository == 'hacs-china/integration'
    name: Generate ${{ matrix.category }} data
    strategy:
      matrix:
        category:
          - appdaemon
          - integration
          - netdaemon
          - plugin
          - python_script
          - theme
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.2.0

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        id: python
        with:
          python-version: "3.x"
          cache: 'pip'
          cache-dependency-path: |
            requirements_base.txt
            requirements_generate_data.txt

      - name: Install dependencies
        run:  |
          bash manage/install_frontend
          pip3 install \
            --disable-pip-version-check install \
            --ignore-installed \
            --constraint constraints.txt \
            --requirement requirements_generate_data.txt \
            --use-deprecated=legacy-resolver


      - name: Generate ${{ matrix.category }} data
        run: python3 -m scripts.data.generate_category_data ${{ matrix.category }}
        env:
          DATA_GENERATOR_TOKEN: ${{ secrets.DATA_GENERATOR_TOKEN }}
          FORCE_REPOSITORY_UPDATE: ${{ inputs.forceRepositoryUpdate }}

      - name: Check if updated
        id: updated
        run: |
          if test -f "outputdata/${{ matrix.category }}/data.json"; then
            echo "updated=true" >> "$GITHUB_OUTPUT"
          else
            echo "updated=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Validate output with JQ
        if: steps.updated.outputs.updated == 'true'
        run: |
          jq -c . outputdata/${{ matrix.category }}/data.json
          jq -c . outputdata/${{ matrix.category }}/repositories.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: steps.updated.outputs.updated == 'true'
        with:
          name: ${{ matrix.category }}
          path: outputdata/${{ matrix.category }}
          if-no-files-found: error
          retention-days: 7

      - name: Commit to Github
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git clone https://x-access-token:$GITHUB_TOKEN@github.com/hacs-china/data.git ../hacs-data
          cp -rf outputdata/${{ matrix.category }} ../hacs-data/
          cd ../hacs-data
          git add -A .
          git commit -m "Generated hacs ${{ matrix.category }} data"
          git push -u https://x-access-token:$GITHUB_TOKEN@github.com/hacs-china/data.git main
